#Reference: https://actions-pipeline.readthedocs.io/en/latest/
name: Update daily

on:
  push:
  workflow_dispatch:
  schedule : 
    - cron : '59 7 * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Access the repo
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: python ./scripts/reddit_daily.py
        
      - name: Commit and push if it changed
        run: |-
          git config user.name "clara8043"
          git config user.email "clara8043@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Get daily reddit data: ${timestamp}" || exit 0
          git push
